name: GitHub Actions Demo

on:
  push:
    branches: [ master ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Test"
